# $Header: /space/home/eng/cjm/cvs/libdprt-ioi/Makefile.common,v 1.1 2013-09-04 15:19:37 cjm Exp $

IOI_HOME			= ioi
LIBDPRT_IOI_SRC_HOME	= $(LIBDPRT_SRC_HOME)/$(IOI_HOME)
LIBDPRT_IOI_BIN_HOME	= $(LIBDPRT_BIN_HOME)/$(IOI_HOME)
LIBDPRT_IOI_DOC_HOME	= $(LIBDPRT_DOC_HOME)/$(IOI_HOME)

#
# $Log: not supported by cvs2svn $
#
